# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CRldA_X50CT7TuOyzeAM4p-5Jaq_kOru
"""



import trimesh

from hy3dgen.shapegen import Hunyuan3DDiTFlowMatchingPipeline

from IPython import get_ipython
from IPython.display import display
import trimesh

pipeline = Hunyuan3DDiTFlowMatchingPipeline.from_pretrained('tencent/Hunyuan3D-2')
mesh = pipeline(image='/content/IMG_20250411_120155_988-EDIT.jpg')[0]

!pip install hy3dgen
from hy3dgen.pipeline_hunyuan3d_flow_matching import Hunyuan3DDiTFlowMatchingPipeline
from IPython import get_ipython
from IPython.display import display
import trimesh

pipeline = Hunyuan3DDiTFlowMatchingPipeline.from_pretrained('tencent/Hunyuan3D-2')
mesh = pipeline(image='/content/IMG_20250411_120155_988-EDIT.jpg')[0]

# Save the mesh in GLB format
trimesh.exchange.export.export_mesh(mesh, '/content/mesanjid.glb')

# Save the mesh in GLB format
trimesh.exchange.export.export_mesh(mesh, '/content/mesanjid.glb')



pipeline = Hunyuan3DDiTFlowMatchingPipeline.from_pretrained('tencent/Hunyuan3D-2')
mesh = pipeline(image='/content/ChatGPT Image Mar 27, 2025, 11_57_30 PM.png')[0]

# Save the mesh in GLB format
trimesh.exchange.export.export_mesh(mesh, '/content/mecheck.glb')